var questionsArr2 = ["What is the best shape",
"Where would you like to go"];

var questionsAnswersArr2 = ["triangle",
"berlin"];

var questionsArr1 = ["Water or ice",
    "Death or life",
    "Summer or Winter",
    "Red or orange",
    "Iron or gold",
    "1948 or 1967",
    "Father or Mother",
    "Vacation or work",
    "Left or Right",
    "single or group",
    "Toad or fingernail",
    "lean or fat",
    "West or East",
    "White or black",
    "Once or twice",
    "Cowboys or Indians",
    "beautiful or beast",
    "Benz or Erik",
    "The or Eighties",
    "Jonathan or David",
    "Fried or fire",
    "Joker or Batman",
    "Plain or mountains",
    "Gold or silver",
    "Drums or Guitar",
    "Chill or Hardcore"
  ];
  var questionsAnswersArr1 = ["ice",
    "Death",
    "Summer",
    "Red",
    "Iron",
    "1967",
    "Mother",
    "work",
    "Right",
    "group",
    "fingernail",
    "fat",
    "East",
    "black",
    "twice",
    "Indians",
    "beast",
    "Benz",
    "The",
    "Jonathan",
    "fire",
    "Batman",
    "mountains",
    "silver",
    "Guitar",
    "Chill"
  ];